<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Version>0.0.3-alpha</Version>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/kleenestar-project/KleeneStar.Templates</RepositoryUrl>
		<EnableDynamicLoading>true</EnableDynamicLoading>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\KleeneStar.Core\src\KleeneStar.Core\KleeneStar.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Internationalization\de" />
		<EmbeddedResource Include="Internationalization\en" />
	</ItemGroup>

</Project>
